package Backend.Server.Entidades.Enums;

public enum TipoAccion {

    CONEXION,
    DESCONEXION,
    INTENTO_CONEXION_FALLIDO,

    ENVIO_MENSAJE,
    RECEPCION_MENSAJE,

    ENVIO_ARCHIVO,
    DESCARGA_ARCHIVO,
    ERROR_ENVIO_ARCHIVO,

    CREACION_USUARIO,
    ACEPTACION_USUARIO,
    RECHAZO_USUARIO,
    MODIFICACION_USUARIO,

    INICIO_SERVIDOR,
    DETENCION_SERVIDOR,
    ERROR_SISTEMA,
    LIMITE_ALCANZADO
}